# Generated by Django 4.1.2 on 2023-07-24 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="thana",
        ),
    ]
