# Generated by Django 4.2.2 on 2023-06-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
