# Generated by Django 4.1.2 on 2023-04-10 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0002_alter_member_team_delete_team"),
        ("organization", "0003_rename_division_thana_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.branch",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="owner",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="peoples.staff",
            ),
        ),
    ]
