# Generated by Django 4.1.2 on 2023-04-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0002_alter_member_team_delete_team"),
        ("organization", "0004_alter_team_branch_alter_team_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.branch",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team",
            name="owner",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="peoples.staff",
            ),
            preserve_default=False,
        ),
    ]
