# Generated by Django 4.1.2 on 2023-04-18 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0002_alter_member_team_delete_team"),
        ("organization", "0005_alter_team_branch_alter_team_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="peoples.staff"
            ),
        ),
    ]
