# Generated by Django 4.1.2 on 2023-06-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0007_basemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.branch",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ME", "Member"),
                    ("BO", "Branch Owner"),
                    ("CL", "Collector"),
                    ("OO", "Organization Owner"),
                    ("OM", "Organization Member"),
                ],
                default="ME",
                max_length=10,
            ),
        ),
    ]
