# Generated by Django 4.1.2 on 2023-06-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0009_alter_team_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
