# Generated by Django 4.1.2 on 2022-10-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('team', 'serial_number')},
        ),
    ]
