# Generated by Django 4.1.2 on 2023-03-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_team"),
        ("peoples", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.team",
            ),
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
