# Generated by Django 4.1.2 on 2023-06-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0003_remove_staff_branch_remove_staff_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
