# Generated by Django 4.1.2 on 2023-06-23 04:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0004_alter_member_mobile_number_alter_staff_mobile_number"),
        ("peoples", "0004_member_created_at_member_updated_at"),
    ]

    operations = []
