# Generated by Django 4.1.2 on 2023-05-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0007_basemodel"),
        ("peoples", "0002_alter_member_team_delete_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Savings",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="organization.basemodel",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("date", models.DateField()),
                ("balance", models.IntegerField(default=0)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="peoples.member"
                    ),
                ),
            ],
            bases=("organization.basemodel",),
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="organization.basemodel",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("date", models.DateField()),
                ("is_paid", models.BooleanField(default=False)),
                ("total_installment", models.IntegerField(default=0)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="peoples.member"
                    ),
                ),
            ],
            bases=("organization.basemodel",),
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.loan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneralTransaction",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="organization.basemodel",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=10,
                    ),
                ),
                ("summary", models.TextField(blank=True, max_length=150)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transaction.transactioncategory",
                    ),
                ),
            ],
            bases=("organization.basemodel",),
        ),
    ]
