# Generated by Django 4.1.2 on 2022-10-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='stuff',
            new_name='staff',
        ),
    ]
