# Generated by Django 4.1.2 on 2022-10-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0002_alter_member_unique_together'),
        ('transaction', '0002_rename_stuff_savings_staff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savings',
            unique_together={('date', 'member')},
        ),
    ]
