# Generated by Django 4.1.2 on 2023-05-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0002_alter_savings_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="savings",
            name="transaction_type",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("withdraw", "Withdraw")],
                default="deposit",
                max_length=10,
            ),
        ),
    ]
