# Generated by Django 4.1.2 on 2023-05-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0004_alter_savings_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="total_due",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loan",
            name="total_paid",
            field=models.IntegerField(default=0),
        ),
    ]
