# Generated by Django 4.1.2 on 2023-05-06 04:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0006_loan_installment_paid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="installment",
            unique_together={("loan", "date")},
        ),
    ]
