# Generated by Django 4.1.2 on 2023-05-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0007_basemodel"),
        ("transaction", "0007_alter_installment_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="savings",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="organization.team",
            ),
            preserve_default=False,
        ),
    ]
