# Generated by Django 4.1.2 on 2023-06-10 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0009_loan_team"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generaltransaction",
            old_name="type",
            new_name="transaction_type",
        ),
    ]
